"""NXDN PN95 dibit scrambler.

NXDN scrambles the on-air dibits (after the LICH) with a fixed pseudo-random
sequence generated by a 9-bit Fibonacci LFSR. Where the PN sequence is ``1`` the
corresponding dibit is inverted by XOR-ing its MSB (``^= 0x2``); where it is
``0`` the dibit is left alone. The operation is its own inverse, so the same
function both scrambles and descrambles.

Reference: DSD-FME ``nxdn_pn95_dibit_scrambler`` (src/nxdn_deperm.c). The LFSR
seed is ``0xE4`` (228); the feedback taps are bits 0 and 4 of the right-shifting
register.
"""

from __future__ import annotations

from typing import List, Sequence

PN95_SEED = 0xE4  # initial LFSR state, per DSD-FME
PN95_MAX_LEN = 182  # longest dibit run NXDN scrambles in one go


def pn95_sequence(length: int, seed: int = PN95_SEED) -> List[int]:
    """Return the first ``length`` bits of the NXDN PN95 sequence.

    Each element is 0 or 1. ``length`` must not exceed :data:`PN95_MAX_LEN`.
    """
    if length < 0:
        raise ValueError("length must be non-negative")
    if length > PN95_MAX_LEN:
        raise ValueError(f"length must be <= {PN95_MAX_LEN}")

    lfsr = seed & 0x1FF  # 9-bit register
    out: List[int] = []
    for _ in range(length):
        # Take the output bit *before* feedback (matches DSD-FME ordering).
        out.append(lfsr & 1)
        # Right-shifting register: taps at bits 0 and 4 feed bit 8.
        bit = ((lfsr >> 4) ^ (lfsr >> 0)) & 1
        lfsr >>= 1
        lfsr |= bit << 8
    return out


def pn95_descramble_dibits(
    dibits: Sequence[int], seed: int = PN95_SEED
) -> List[int]:
    """De/scramble a run of dibits in place-style (returns a new list).

    Each dibit is an int in ``0..3``. Self-inverse: applying twice yields the
    original sequence.
    """
    seq = pn95_sequence(len(dibits), seed=seed)
    out: List[int] = []
    for d, p in zip(dibits, seq):
        if d < 0 or d > 3:
            raise ValueError(f"dibit out of range: {d!r}")
        if p:
            d = (d ^ 0x2) & 0x3
        out.append(d)
    return out


# Scrambling and descrambling are the same operation.
pn95_scramble_dibits = pn95_descramble_dibits
